services:
  postgres:
    image: postgres:17-alpine
    container_name: university-club-website-network-postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  django:
    container_name: university-club-website-network-django
    restart: always
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
networks:
  default:
    name: university-club-website-network
volumes:
  postgres_data: